#!/bin/bash

ROLE="arn:aws:iam::659454872679:role/OrganizationAccountAccessRole"
JSON=$(aws sts assume-role --role-arn $ROLE --role-session-name "ci-build" --profile default)
export AWS_ACCESS_KEY_ID=$(echo $JSON | jq -r '.Credentials.AccessKeyId')
export AWS_SECRET_ACCESS_KEY=$(echo $JSON | jq -r '.Credentials.SecretAccessKey')
export AWS_SESSION_TOKEN=$(echo $JSON | jq -r '.Credentials.SessionToken')

make clean
make
